version: 2
jobs:
  build-deploy-release-branches:
    docker:
      - image: circleci/node:11.5.0
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          key: project-name-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Install node.js dependencies
          command: npm i
      - save_cache:
          key: project-name-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Run unit tests
          command: npm run test
      - run:
          name: Build
          command: npm run build
      - run:
          name: Run semantic-release to generate new git tags and next version
          command: npm run semantic-release

  build-deploy-feature-branch:
    docker:
      - image: circleci/node:11.5.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: project-name-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm i
      - save_cache:
          key: project-name-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Run unit tests
          command: npm run test
      - run:
          name: Build the source
          command: npm run build

workflows:
  version: 2
  build-release-branches:
    jobs:
      - build-deploy-release-branches:
          filters:
            branches:
              only:
                - alpha
                - beta
                - master
                - next
  build-feature-branch:
    jobs:
      - build-deploy-feature-branch:
          filters:
            branches:
              only:
                - /experiment.*/
                - /feature.*/
                - /fix.*/
